{% set version = "0.1.7" %}
  {% set version = "0.1.6" %}

package:
  name: compass-interface-core
  version: {{ version }}

source:
  url: https://github.com/the-scouts/compass-interface-core/releases/download/v{{ version }}/compass-interface-core-{{ version }}.tar.gz
  sha256: d29d67dba7ce8bffb0f6ca0b68c88ce414a42c49a8797f2b9757d19cb5bf829d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - certifi
    - lxml
    - pandas
    - python-dateutil
    - requests

test:
  imports:
    - compass

about:
  home: https://github.com/the-scouts/compass-interface-core
  license: MIT
  license_file: LICENSE
  summary: The unofficial API to the TSA Compass membership database

extra:
  recipe-maintainers:
    - AA-Turner
    - rglss
